Vagrant.configure("2") do |config|
	config.vm.provision "shell", inline: "echo hello"
	
	config.vm.define "web" do |web|
		web.vm.box = "ubuntu/xenial64"
		web.vm.network "public_network"
		web.vm.network "private_network", ip: "192.168.1.22"
		web.vm.provider "virtualbox" do |vb|
		  vb.memory = "1600"
		  vb.cpus = "2"
		end
	end
	
	config.vm.define "db" do |db|
		db.vm.box = "centos/7"
		db.vm.network "public_network"
		db.vm.network "private_network", ip:"192.168.1.33"
	end
end